# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cuddlywasp-ssr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run bootstrap --if-present
          npm run next:build --if-present
      
      - name: 7z release
        run: 7z a -t7z -mx=9 release.7z .
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.1
        with:
          name: node-app
          path: release.7z

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3.0.1
        with:
          name: node-app
          
      - name: Un7z release
        run: 7z x release.7z

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cuddlywasp-ssr'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A348225F04304E33B09091748BE07580 }}
          package: .
          startup-command: npm run start:production
